name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.8-rc-4
      - uses: actions/checkout@v2
    
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: "11"
      - name: Give Rights
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --warning-mode=all --stacktrace
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
